### PR TITLE
Add initial support for EMACS

### PR DESCRIPTION
**Pull request by j-mckitrick**

### CODE REVIEW

**Comment by j-mckitrick** [comment]
@joeferraro Are you still interested in this feature?

**Comment by ralphcallaway** [comment]
@j-mckitrick I'd assume yes, however, the core module is in the process of being re-written in node, see https://github.com/joeferraro/MavensMate, you might consider contributing changes to that repo as well

happy to take a look at integrating this still since I don't know when the current python implementation will start getting phased out

**Comment by j-mckitrick** [comment]
@ralphcallaway So this is quite interesting.  It looks like a drop-in replacement for the original that was written in python.  Assuming it all works the same, I definitely want to switch my emacs support to work with the new version.

**Comment by j-mckitrick** [comment]
@ralphcallaway are you still interested in integrating emacs support?  Since I have used MM for my SF development, I'd rather not learn node just to contribute a patch to keep using it.  If the python version will be around for a while, that's what I'd prefer for now.  Are you the new maintainer of the python version?

**Comment by joeferraro** [comment]
sorry for the slow action on this PR, guys, I've been re-writing the core for the past several months (https://github.com/joeferraro/MavensMate) to better support editors beyond ST and Atom (VS Code being next-in-line in conjunction with Microsoft). The first step for us is to create a GitHub repo and start integrating Emacs with the core. Given the documentation for the new core has not yet been updated, I'm the best resource for anyone building a plugin.

**Comment by j-mckitrick** [comment]
Is this the python core or the node rewrite?

On Tue, Aug 11, 2015 at 10:00 AM Joe Ferraro <notifications@github.com>
wrote:

> sorry for the slow action on this PR, guys, I've been re-writing the core
> for the past several months (https://github.com/joeferraro/MavensMate) to
> better support editors beyond ST and Atom (VS Code being next-in-line in
> conjunction with Microsoft). The first step for us is to create a GitHub
> repo and start integrating Emacs with the core. Given the documentation for
> the new core has not yet been updated, I'm the best resource for anyone
> building a plugin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/mm/pull/11#issuecomment-129886664>.
>
-- 
Jonathon McKitrick

**Comment by joeferraro** [comment]
> this

what's this?

**Comment by j-mckitrick** [comment]
The core you are rewriting.

Ralph said some time ago the core was being rewritten in node.  But then I
saw recent activity here in the python version.  So I'd like to know which
to follow, which to contribute to, and which you are moving forward with.

On Tue, Aug 11, 2015 at 10:20 AM Joe Ferraro <notifications@github.com>
wrote:

> this
>
> what's this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/mm/pull/11#issuecomment-129900286>.
>
-- 
Jonathon McKitrick

**Comment by joeferraro** [comment]
>  I've been re-writing the core
 for the past several months (https://github.com/joeferraro/MavensMate) to
 better support editors beyond ST and Atom

**Comment by j-mckitrick** [comment]
So what is the current state of mm, the python version?

On Tue, Aug 11, 2015 at 10:38 AM Joe Ferraro <notifications@github.com>
wrote:

> I've been re-writing the core
> for the past several months (https://github.com/joeferraro/MavensMate) to
> better support editors beyond ST and Atom
>
> —
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/mm/pull/11#issuecomment-129909878>.
>
-- 
Jonathon McKitrick

**Comment by joeferraro** [comment]
> Keep in mind, the APIs in this project (mm) are deprecated.

**Comment by j-mckitrick** [comment]
So 2 questions:

1.  Where is the mm functionality going to be after the
rewrite/deprecation, etc?
2.  Where (if anywhere) would I contribute to support emacs?


On Tue, Aug 11, 2015 at 11:00 AM Joe Ferraro <notifications@github.com>
wrote:

> Keep in mind, the APIs in this project (mm) are deprecated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/mm/pull/11#issuecomment-129919366>.
>
-- 
Jonathon McKitrick

**Comment by joeferraro** [comment]
1. most, if not all mm functionality exists today in this project: https://github.com/joeferraro/MavensMate
2. no emacs support exists today. however, writing net-new plugins is straightforward thanks to the rewrite. as long as your editor supports making local HTTP requests, then any command can be run very simply over HTTP: https://github.com/joeferraro/MavensMate-SublimeText/blob/node/lib/cli.py#L129

what platform are you on, OSX, Linux? If so, you can install `mavensmate-app` today, which hosts the MavensMate UI and runs a local HTTP server on port 56248 that can be hit from your editor plugin. see how ST is doing it today: https://github.com/joeferraro/MavensMate-SublimeText/blob/node/lib/cli.py#L129

Example:
> POST http://localhost:56248/execute?command=new-project&async=1
{
    "username" : "foo@bar.com",
    "password" : "force",
    "name" : "myproject",
    "workspace": "/some/workspace"
}

I know the APIs the best at this point, so if you want to create a repo (or I can) for the emacs plugin then we can collaborate via tickets there

**Comment by j-mckitrick** [comment]
Cool, thanks for the details.

What I have now is a simple emacs module that builds requests as JSON,
dumps them to a file, and pipes it to mm for execution.  Then I parse the
results.  That's been working for a while, but I took a hiatus from SF
development.  Now that I'm touching SF code again, it might make sense to
sync up with the latest.  My goal was not to need Eclipse to work with SF.

Very little needed to be changed on the mm side to support emacs.  The
majority of the work was adding debug output to see what needed to be sent
via JSON for each of the SF operations I wanted to support.


On Tue, Aug 11, 2015 at 11:27 AM Joe Ferraro <notifications@github.com>
wrote:

>
>    1. most, if not all mm functionality exists today in this project:
>    https://github.com/joeferraro/MavensMate
>    2. no emacs support exists today. however, writing net-new plugins is
>    straightforward thanks to the rewrite. as long as your editor supports
>    making local HTTP requests, then any command can be run very simply over
>    HTTP:
>    https://github.com/joeferraro/MavensMate-SublimeText/blob/node/lib/cli.py#L129
>
> what platform are you on, OSX, Linux? If so, you can install
> mavensmate-app today, which hosts the MavensMate UI and runs a local HTTP
> server on port 56248 that can be hit from your editor plugin. see how ST is
> doing it today:
> https://github.com/joeferraro/MavensMate-SublimeText/blob/node/lib/cli.py#L129
>
> Example:
>
> POST http://localhost:56248/execute?command=new-project&async=1
> {
> "username" : "foo@bar.com",
> "password" : "force",
> "name" : "myproject",
> "workspace": "/some/workspace"
> }
>
> I know the APIs the best at this point, so if you want to create a repo
> (or I can) for the emacs plugin then we can collaborate via tickets there
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/mm/pull/11#issuecomment-129929592>.
>
-- 
Jonathon McKitrick

**Comment by j-mckitrick** [comment]
So @joeferraro @ralphcallaway tell me if I understand correctly: most (eventually all) of the `mm` functionality has been integrated into the monolithic `MavensMate` project and that's the preferred way for plugins to access all of these SF API integration features?

**Comment by joeferraro** [comment]
@j-mckitrick correct

**Comment by j-mckitrick** [comment]
Will the command line interface be going away with the move to http?  Or will it continue to be supported?

**Comment by joeferraro** [comment]
cli will be supported. updated documentation to come, but the payloads are similar to `mm`

**Comment by AltiusRupert** [comment]
Hi Jonathon,
What has become of your work to integrate Emacs with MM ?

Rupert

**Comment by j-mckitrick** [comment]
I'm still using the Python version, but could be convinced to move to the
NodeJS version if the migration is relatively painless.  I'm still
interesting in working on an emacs mode for compilation, but right now just
have a collection of functions that I use.

On Tue, Dec 29, 2015 at 7:56 AM Rupert Barrow <notifications@github.com>
wrote:

> Hi Jonathon,
> What has become of your work to integrate Emacs with MM ?
>
> Rupert
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/mm/pull/11#issuecomment-167783236>.
>
-- 
Jonathon McKitrick

**Comment by j-mckitrick** [comment]
Is anyone interested?

On Tue, Dec 29, 2015 at 8:22 AM <jmckitrick@gmail.com> wrote:

> I'm still using the Python version, but could be convinced to move to the
> NodeJS version if the migration is relatively painless.  I'm still
> interesting in working on an emacs mode for compilation, but right now just
> have a collection of functions that I use.
>
> On Tue, Dec 29, 2015 at 7:56 AM Rupert Barrow <notifications@github.com>
> wrote:
>
>> Hi Jonathon,
>> What has become of your work to integrate Emacs with MM ?
>>
>> Rupert
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joeferraro/mm/pull/11#issuecomment-167783236>.
>>
> --
> Jonathon McKitrick
>
-- 
Jonathon McKitrick

**Comment by AltiusRupert** [comment]
Yes, quite so if it improves performance of Save/Recompile vs. SublimeText MM.
Rupert

**Comment by j-mckitrick** [comment]
Are you referring to switching to the NodeJS version?

On Tue, Jan 5, 2016 at 12:20 PM Rupert Barrow <notifications@github.com>
wrote:

> Yes, quite so if it improves performance of Save/Recompile vs. SublimeText
> MM.
> Rupert
>
>
> > Le 5 janv. 2016 à 17:00, Jonathon McKitrick <notifications@github.com>
> a écrit :
> >
> > Is anyone interested?
> >
> > On Tue, Dec 29, 2015 at 8:22 AM <jmckitrick@gmail.com> wrote:
> >
> > > I'm still using the Python version, but could be convinced to move to
> the
> > > NodeJS version if the migration is relatively painless. I'm still
> > > interesting in working on an emacs mode for compilation, but right now
> just
> > > have a collection of functions that I use.
> > >
> > > On Tue, Dec 29, 2015 at 7:56 AM Rupert Barrow <
> notifications@github.com>
> > > wrote:
> > >
> > >> Hi Jonathon,
> > >> What has become of your work to integrate Emacs with MM ?
> > >>
> > >> Rupert
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/joeferraro/mm/pull/11#issuecomment-167783236>.
> > >>
> > > --
> > > Jonathon McKitrick
> > >
> > --
> > Jonathon McKitrick
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/joeferraro/mm/pull/11#issuecomment-169043767>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/mm/pull/11#issuecomment-169069284>.
>
-- 
Jonathon McKitrick

**Comment by ralphcallaway** [comment]
@AltiusRupert i've been using the node version and it's been a lot faster, however, winter '16 initially was a lot slower, as with any performance stuff you're mileage will vary and the biggest factor is going to be salesforce performance. and not sure if you were asking if emacs would improve performance, but i wouldn't expect that since every editor uses the same mavensmate core

**Pull request closed without merging**
